### ISSUE TITLE
Is it possible to merge this into `systemd/node-systemd`?

### ISSUE THREAD

**Issue by paluh** [jue89/node-systemd-journald#10]
As a developer I'm really confused because there are "official" bindings for node provided on `github.com/systemd` account and there is your lib which works on newer node versions (as far as I understand your `README.Why` section).

Have you considered proposing your bindings as a replacement for `github.com/systemd/node-systemd`? I mean something like opening pull request or issue there.

**Comment by jue89** [comment]
Hi paluh!

I had several reasons that kept me from merging my code into the official project in the first place:
 * My API is completely different. I pulled in some abstraction to hide some internals of journald. This leads to more readable code. (My API: ```log.info('foobar');``` vs. the official API: ```journald('MESSAGE=foobar', 'PRIORITY=6');```)
 * The project seemed to be abandoned in 2015. And it still does today. Issues and PRs are not answered.
 * I wanted to be able to call ```npm publish``` asap, when I started this project. This conflicts also with reason no. 2.

But maybe we can move this project to the systemd organisation if the systemd guys want this project inside (and give me the right to maintain it). I need some time to think about this.

I hope this helps to understand why.

**Comment by paluh** [comment]
Thanks for explanation, @jue89!

I understand your motivation better now. The only thing is that I'm afraid that many developers can be somewhat skeptical about future/maintenance of "unofficial" library. Ironically it is other way around in this case as you described above ;-)

Anyway, thanks for sharing your work and thoughts!

P.S.
I've just published Purescript bindings to your library: 

https://pursuit.purescript.org/packages/purescript-systemd-journald/0.1.1

**Comment by jue89** [comment]
Nice!

And thank you for testing out the ```fields``` option. Nice collection to demonstrate what's possible.
