### ISSUE TITLE
How do you read journald without calling sd_journal_open?

### ISSUE THREAD

**Issue by JonathanWilbur** [jue89/node-systemd-journald#22]
I noticed in your code that you never call `sd_journal_open`. Is the journal already opened by the NodeJS runtime or something?

Thanks in advance!

**Comment by jue89** [comment]
This library just writes to the journal and doesn't read. Thus, `sd_journal_send` is the only required method for this library to work ;-)

**Comment by JonathanWilbur** [comment]
Oh I see. Okay. Thank you!
